### PR TITLE
add share on fb button to map

### PR DESCRIPTION
**Pull request by mixcas**
must run: `cordova plugin add cordova-plugin-x-socialsharing && cordova prepare`

### CODE REVIEW

**Comment by varffs** [comment]
did you test this on device?

**Comment by varffs** [comment]
doesn't work on ios and imo this is a bad implimentation. Should be part of the Game object rather than anon function.

**Comment by mixcas** [comment]
U r rite, it should be part of `Game`
did u install the plugin tho?

**Comment by varffs** [comment]
and it already have conflicts. Going to just delete this PR and branch and write it again.

**Comment by mixcas** [comment]
lol ok…

**Pull request closed without merging**
