### PR TITLE
add Social Sharing

### PR DESCRIPTION
**Pull request by varffs**

### CODE REVIEW

**Comment by varffs** [comment]
This opens the share dialog on iOS meaning people can share however they want. Needs testing on Droid

**Comment by varffs** [comment]
We need a proper URL to set for the share that is about Walking Game. Probably that will be something on <confidential!>'s website

**Comment by varffs** [comment]
For the image we should probably generate an image using canvas and a graphic and the number of points and the player name. Should that go in this PR/branch?

**Comment by mixcas** [comment]
whats the plugin?

**Comment by varffs** [comment]
same as before. its very similar just a the general function and called from a different place

**Pull request merged**
